name: Build and Release Snippy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build Snippy
        run: |
          pyinstaller snippy/main.py --name snippy --collect-all snippy --collect-data emoji --onedir --clean
          cd dist/snippy
          tar -czvf ../../snippy-${{ github.ref_name }}.tar.gz *

      - name: Calculate SHA256
        id: sha256
        run: shasum -a 256 snippy-${{ github.ref_name }}.tar.gz | awk '{ print $1 }'

      - name: Create Release in Formula Repository
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.FORMULA_REPO_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/narashin/homebrew-snippy/releases \
            -d '{
              "tag_name": "${{ github.ref_name }}",
              "name": "${{ github.ref_name }}",
              "body": "Automated release by GitHub Actions",
              "draft": false,
              "prerelease": false
            }'

      - name: Upload Asset to Release
        run: |
          release_id=$(curl -H "Authorization: token ${{ secrets.FORMULA_REPO_ACCESS_TOKEN }}" https://api.github.com/repos/narashin/homebrew-snippy/releases/tags/${{ github.ref_name }} | jq -r '.id')
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.FORMULA_REPO_ACCESS_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @snippy-${{ github.ref_name }}.tar.gz \
            https://uploads.github.com/repos/narashin/homebrew-snippy/releases/$release_id/assets?name=snippy-${{ github.ref_name }}.tar.gz

      - name: Update Formula File
        run: |
          git clone https://x-access-token:${{ secrets.FORMULA_REPO_ACCESS_TOKEN }}@github.com/narashin/homebrew-snippy.git
          cd homebrew-snippy
          sed -i '' "s|url \".*\"|url \"https://github.com/narashin/snippy/releases/download/${{ github.ref_name }}/snippy-${{ github.ref_name }}.tar.gz\"|" Formula/snippy.rb
          sed -i '' "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" Formula/snippy.rb
          git config user.name "narashin"
          git config user.email "me@nara.dev"
          git add Formula/snippy.rb
          git commit -m "Update Snippy to version ${{ github.ref_name }}"
          git push